name: 'Azure Key Vault Sync'
description: 'Fetch Key Vault secrets and create repo secrets'
inputs:
  keyvault: 
    description: 'Name of the key vault to fetch secrets from'
    required: true
    default: 'none'
  token:
    description: 'Github PAT with public key and repo permissions'
    required: true
    default: 'none'
runs:
  using: 'node16'
  main: 'index.js'
