

name: Build and Push Images

on:
  push:
    tags: 
      - '**' 
    paths-ignore: 
      - README.md
      - .gitignore
      - .github/**
  workflow_dispatch:
    
jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v3

    - name: Azure Login
      uses: Azure/login@v1

    - name: Run w/ Node
      run: node fetch.js