name: test azure login 

permissions: write-all

on:
  push:
    branches:
      - main
    paths-ignore: 
      - README.md
      - .gitignore
      - .github/**
  workflow_dispatch:
    
jobs:
  azure:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v3

    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run w/ Node
      run: |
        export TOKEN=${{ secrets.GH_PAT }}
        node index.js